print("Say hello to the new student")
name = input("What is your students name?")
age = input("How old is she?")
place = input("Where does she live?")
print(00000)
print(00000)
print("This is a new classmate")
print("Her name is", name)
print("She is", age, "years old")
print("She lives at", place)
